export const CHANGE_MSG = 'CHANGE_MSG';
export const CHANGE_FIELD = 'CHANGE_FIELD';
export const RESET_FIELDS = 'RESET_FIELDS';
export const CHANGE_STATUS_TO_SUCCESS = 'CHANGE_STATUS_TO_SUCCESS';
export const CHANGE_STATUS_TO_FAILED = 'CHANGE_STATUS_TO_FAILED';