export const MAKE_FOLDER_ACTIVE = 'MAKE_FOLDER_ACTIVE';
export const ADD_NEW_NOTE = 'ADD_NEW_NOTE';
export const GET_ALL_NOTES = 'GET_ALL_NOTES';
export const GO_TO_NOTE_EDIT = 'GO_TO_NOTE_EDIT';
export const GO_TO_NOTE_CREATION = 'GO_TO_NOTE_CREATION';
