# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('secondName', models.TextField()),
                ('email', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
    ]
