# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-31 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0005_auto_20170731_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
