# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0006_auto_20170731_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dinosaurs.Folder'),
            preserve_default=False,
        ),
    ]
