# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0008_auto_20171009_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
