# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0009_auto_20171028_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dinosaurs.User'),
            preserve_default=False,
        ),
    ]
