# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0011_auto_20171102_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dinosaurs.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaurs.Person'),
        ),
    ]
