# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0016_auto_20171107_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='dinosaurs.Person'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dinosaurs.Person'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dinosaurs.Folder'),
        ),
    ]
